/** plugins  message events */
export const enum PLUGIN_EVENT  {
  PUB_JOINED = 'joined',
  SUB_JOINED = 'subscribed',
  PUB_LIST = 'publisher_list',
  PARTICIPANTS_LIST = 'participants_list',
  PUB_PEER_JOINED = 'publisher_joined',
  STARTED = 'started',
  PAUSED = 'paused',
  SWITCHED = 'switched',
  CONFIGURED = 'configured',
  SLOW_LINK = 'slowlink',
  DISPLAY = 'display',
  UNPUBLISHED = 'unpublished',
  LEAVING = 'leaving',
  UPDATED = 'updated',
  KICKED = 'kicked',
  RECORDING_ENABLED_STATE = 'recording_enabled_state',
  TALKING = 'talking',
  SC_SUBSTREAM_LAYER = 'sc_substream_layer',
  SC_TEMPORAL_LAYERS = 'sc_temporal_layers',
  ALLOWED = 'allowed',
  EXISTS = 'exists',
  ROOMS_LIST = 'list',
  CREATED = 'created',
  DESTROYED = 'destroyed',
  RTP_FWD_STARTED = 'rtp_fwd_started',
  RTP_FWD_STOPPED = 'rtp_fwd_stopped',
  RTP_FWD_LIST = 'rtp_fwd_list',
  SUCCESS = 'success',
  ERROR = 'error',
  REMOTE_TRACK = 'remotetrack',
  MESSAGE = 'message'
}
