export const enum AppMutationTypes {
  SET_WEBRTCSESSION_ID = 'SET_WEBRTCSESSION_ID',
  SET_CHATSESSION_ID = 'SET_CHATSESSION_ID',
  SET_DEVICE = 'SET_DEVICE',
  REMOVE_ALL_DEVICES = 'REMOVE_ALL_DEVICES'
}
