name: Semantic Release
on:
  push:
    branches: 
      - main
      - beta
  pull_request:
    branches:
      - main

concurrency: production

env:
  BUILD_ARTIFACT: 'build-artifact'
  ARTIFACT_PATH: 'dist'
  VITE_ACCESS_TOKEN: ${{ vars.vite_build.VITE_ACCESS_TOKEN }}
  VITE_AMOUNT: ${{ vars.VITE_AMOUNT }}
  VITE_IS_AUTHENTIFICATED: ${{ vars.VITE_IS_AUTHENTIFICATED }}
  VITE_STORAGE_KEY: ${{ vars.VITE_STORAGE_KEY }}
  VITE_USER_DATA: ${{ vars.VITE_USER_DATA }}
  VITE_WEBRTC_SERVER: ${{ vars.VITE_WEBRTC_SERVER }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: touch .env.local
    - run: env
    - run: echo "VITE_ACCESS_TOKEN=${{ env.VITE_ACCESS_TOKEN }}" >> .env.local
    - run: echo "VITE_AMOUNT=$VITE_AMOUNT" >> .env.local
    - run: echo "VITE_IS_AUTHENTIFICATED=$VITE_IS_AUTHENTIFICATED" >> .env.local
    - run: echo "VITE_STORAGE_KEY=$VITE_STORAGE_KEY" >> .env.local
    - run: echo "VITE_USER_DATA=$VITE_USER_DATA" >> .env.local
    - run: echo "VITE_WEBRTC_SERVER=$VITE_WEBRTC_SERVER" >> .env.local
    - run: cat .env.local
    - run: echo "var is ${VITE_WEBRTC_SERVER} ${{ vars.vite_build.VITE_WEBRTC_SERVER}}"
    - run: npm ci
    - run: npm run build --if-present
    - run: tar -cvf "${{ env.ARTIFACT_PATH }}.tar.gz" ${{env.ARTIFACT_PATH }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: "${{ env.ARTIFACT_PATH }}.tar.gz"
    
  semantic:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: "${{ env.ARTIFACT_PATH }}.tar.gz"
      - run: ls -1lr
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROXY_HOST }}
          username: ${{ secrets.PROXY_USERNAME }}
          key: ${{ secrets.PROXY_KEY }}
          port: ${{ secrets.PROXY_PORT }}
          passphrase: ${{ secrets.PROXY_PASSPHRASE }}
          source: "${{ env.ARTIFACT_PATH }}.tar.gz"
          target: /var/www/html/trft
