name: Semantic Release
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_ARTIFACT: 'build-artifact'
  ARTIFACT_PATH: 'dist'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: ${{ env.ARTIFACT_PATH }}
    
  semantic:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ${{ env.ARTIFACT_PATH }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
